USE [master]
GO
/****** Object:  Database [AicharCoupon]    Script Date: 3/27/2022 11:11:37 AM ******/
CREATE DATABASE [AicharCoupon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AicharCoupon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AicharCoupon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AicharCoupon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AicharCoupon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AicharCoupon] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AicharCoupon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AicharCoupon] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AicharCoupon] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AicharCoupon] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AicharCoupon] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AicharCoupon] SET ARITHABORT OFF 
GO
ALTER DATABASE [AicharCoupon] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AicharCoupon] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AicharCoupon] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AicharCoupon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AicharCoupon] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AicharCoupon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AicharCoupon] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AicharCoupon] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AicharCoupon] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AicharCoupon] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AicharCoupon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AicharCoupon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AicharCoupon] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AicharCoupon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AicharCoupon] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AicharCoupon] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [AicharCoupon] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AicharCoupon] SET RECOVERY FULL 
GO
ALTER DATABASE [AicharCoupon] SET  MULTI_USER 
GO
ALTER DATABASE [AicharCoupon] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AicharCoupon] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AicharCoupon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AicharCoupon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AicharCoupon] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AicharCoupon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AicharCoupon', N'ON'
GO
ALTER DATABASE [AicharCoupon] SET QUERY_STORE = OFF
GO
USE [AicharCoupon]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 3/27/2022 11:11:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Coupons]    Script Date: 3/27/2022 11:11:38 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Coupons](
	[CouponId] [int] IDENTITY(1,1) NOT NULL,
	[CouponCode] [nvarchar](max) NULL,
	[DiscountAmount] [float] NOT NULL,
 CONSTRAINT [PK_Coupons] PRIMARY KEY CLUSTERED 
(
	[CouponId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [AicharCoupon] SET  READ_WRITE 
GO
