USE [master]
GO
/****** Object:  Database [AicharShoppingCart]    Script Date: 3/27/2022 11:17:12 AM ******/
CREATE DATABASE [AicharShoppingCart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AicharShoppingCart', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AicharShoppingCart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AicharShoppingCart_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AicharShoppingCart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AicharShoppingCart] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AicharShoppingCart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AicharShoppingCart] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET ARITHABORT OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AicharShoppingCart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AicharShoppingCart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AicharShoppingCart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AicharShoppingCart] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [AicharShoppingCart] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET RECOVERY FULL 
GO
ALTER DATABASE [AicharShoppingCart] SET  MULTI_USER 
GO
ALTER DATABASE [AicharShoppingCart] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AicharShoppingCart] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AicharShoppingCart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AicharShoppingCart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AicharShoppingCart] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AicharShoppingCart] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AicharShoppingCart', N'ON'
GO
ALTER DATABASE [AicharShoppingCart] SET QUERY_STORE = OFF
GO
USE [AicharShoppingCart]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 3/27/2022 11:17:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CartDetails]    Script Date: 3/27/2022 11:17:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CartDetails](
	[CartDetailsId] [int] IDENTITY(1,1) NOT NULL,
	[CartHeaderId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Count] [int] NOT NULL,
 CONSTRAINT [PK_CartDetails] PRIMARY KEY CLUSTERED 
(
	[CartDetailsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CartHeaders]    Script Date: 3/27/2022 11:17:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CartHeaders](
	[CartHeaderId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](max) NULL,
	[CouponCode] [nvarchar](max) NULL,
 CONSTRAINT [PK_CartHeaders] PRIMARY KEY CLUSTERED 
(
	[CartHeaderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 3/27/2022 11:17:12 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Price] [float] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[CategoryName] [nvarchar](max) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_CartDetails_CartHeaderId]    Script Date: 3/27/2022 11:17:12 AM ******/
CREATE NONCLUSTERED INDEX [IX_CartDetails_CartHeaderId] ON [dbo].[CartDetails]
(
	[CartHeaderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CartDetails_ProductId]    Script Date: 3/27/2022 11:17:12 AM ******/
CREATE NONCLUSTERED INDEX [IX_CartDetails_ProductId] ON [dbo].[CartDetails]
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CartDetails]  WITH CHECK ADD  CONSTRAINT [FK_CartDetails_CartHeaders_CartHeaderId] FOREIGN KEY([CartHeaderId])
REFERENCES [dbo].[CartHeaders] ([CartHeaderId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CartDetails] CHECK CONSTRAINT [FK_CartDetails_CartHeaders_CartHeaderId]
GO
ALTER TABLE [dbo].[CartDetails]  WITH CHECK ADD  CONSTRAINT [FK_CartDetails_Products_ProductId] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([ProductId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CartDetails] CHECK CONSTRAINT [FK_CartDetails_Products_ProductId]
GO
USE [master]
GO
ALTER DATABASE [AicharShoppingCart] SET  READ_WRITE 
GO
