USE [master]
GO
/****** Object:  Database [AicharProducts]    Script Date: 3/27/2022 11:16:32 AM ******/
CREATE DATABASE [AicharProducts]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AicharProducts', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AicharProducts.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AicharProducts_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AicharProducts_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AicharProducts] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AicharProducts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AicharProducts] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AicharProducts] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AicharProducts] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AicharProducts] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AicharProducts] SET ARITHABORT OFF 
GO
ALTER DATABASE [AicharProducts] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AicharProducts] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AicharProducts] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AicharProducts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AicharProducts] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AicharProducts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AicharProducts] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AicharProducts] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AicharProducts] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AicharProducts] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AicharProducts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AicharProducts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AicharProducts] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AicharProducts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AicharProducts] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AicharProducts] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [AicharProducts] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AicharProducts] SET RECOVERY FULL 
GO
ALTER DATABASE [AicharProducts] SET  MULTI_USER 
GO
ALTER DATABASE [AicharProducts] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AicharProducts] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AicharProducts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AicharProducts] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AicharProducts] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AicharProducts] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AicharProducts', N'ON'
GO
ALTER DATABASE [AicharProducts] SET QUERY_STORE = OFF
GO
USE [AicharProducts]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 3/27/2022 11:16:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 3/27/2022 11:16:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Price] [float] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[CategoryName] [nvarchar](max) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [AicharProducts] SET  READ_WRITE 
GO
